### ISSUE TITLE
Look at who has ADMIN

### ISSUE THREAD

**Issue by garethahealy** [redhat-cop/org#1000]
Off the back of the below, let's look at who has ADMIN and whether they need it. Certain teams should have ADMIN but I feel that should be called out in the team name. Those who do not need ADMIN should be MAINTAINER or similar.
- https://github.com/redhat-cop/org/pull/997#issuecomment-2612093518

**Comment by garethahealy** [comment]
@redhat-cop/redhat-cop-sre

**Comment by garethahealy** [comment]
before i go ahead and make changes to the `config.yaml` - wanted some feedback.

so my current idea is to follow these rules/style:
 - top level team is only membership, doesn't include repos
 - child team for admins and merges

so the below which is now:

```
agnosticd-core:
  description: Core team members for the agnosticd project.
  maintainers:
    - agonzalezrh
    - fridim
    - jkupferer
    - newgoliath
    - prakhar1985
    - rut31337
    - tonykay
    - wkulhanek
  members: []
  privacy: closed
  repos:
    agnosticd: admin
```

would become:

```
agnosticd-core:
  description: Core team members for the agnosticd project.
  members:
    - agonzalezrh
    - fridim
    - jkupferer
    - newgoliath
    - prakhar1985
    - rut31337
    - tonykay
    - wkulhanek
  privacy: closed
  teams:
    agnosticd-core-admins:
      description: Core admin members for the agnosticd project.
      maintainers:
        - agonzalezrh
        - fridim
        - jkupferer
        - newgoliath
        - prakhar1985
        - rut31337
        - tonykay
        - wkulhanek
      privacy: closed
      repos:
        agnosticd: admin
```

and containers-cop as-is:

```
      container-cop:
        description: Contributors to the Containers & PaaS CoP
        maintainers:
          - etsauer
          - oybed
          - sabre1041
        members:
          - abaird-rh
          - bbeaudoin
          - beelandc
          - bszeti
          - ckavili
          - davgordo
          - drichtarik
          - garethahealy
          - huddlesj
          - infosec812
          - jaredburck
          - jimdillon
          - jooho
          - juliaaano
          - juozasa
          - kkoller
          - linuxstudio
          - lpsantil
          - luckylittle
          - makentenza
          - malacourse
          - mathianasj
          - mike4263
          - mophahr
          - mwitzenm
          - noelo
          - pabrahamsson
          - raffaelespazzoli
          - rpelisse
          - samueltauil
          - shah-zobair
          - springdo
          - stocky37
          - themoosman
          - vvaldez
        privacy: closed
        repos: {}
        teams:
          bats:
            description: Bash Automation Testing System
            maintainers:
              - ckavili
              - garethahealy
              - pabrahamsson
              - springdo
            privacy: closed
            repos: {}
            teams:
              bats-mergers:
                description: BATS Mergers & Admins
                maintainers:
                  - ckavili
                  - garethahealy
                  - pabrahamsson
                  - springdo
                privacy: closed
                repos:
                  bats-library: admin
```

would become:

```
      container-cop:
        description: Contributors to the Containers & PaaS CoP
        members:
          - etsauer
          - oybed
          - sabre1041
          - abaird-rh
          - bbeaudoin
          - beelandc
          - bszeti
          - ckavili
          - davgordo
          - drichtarik
          - garethahealy
          - huddlesj
          - infosec812
          - jaredburck
          - jimdillon
          - jooho
          - juliaaano
          - juozasa
          - kkoller
          - linuxstudio
          - lpsantil
          - luckylittle
          - makentenza
          - malacourse
          - mathianasj
          - mike4263
          - mophahr
          - mwitzenm
          - noelo
          - pabrahamsson
          - raffaelespazzoli
          - rpelisse
          - samueltauil
          - shah-zobair
          - springdo
          - stocky37
          - themoosman
          - vvaldez
        privacy: closed
        repos: {}
        teams:
          bats:
            description: Bash Automation Testing System
            members:
              - ckavili
              - garethahealy
              - pabrahamsson
              - springdo
            privacy: closed
            repos: {}
            teams:
              bats-admins:
                description: BATS Mergers & Admins
                maintainers:
                  - ckavili
                  - garethahealy
                  - pabrahamsson
                  - springdo
                privacy: closed
                repos:
                  bats-library: admin
```
